Spring:
#  redis
  redis:
    host: 127.0.0.1
    port: 6379

#  profiles:
#    ?active: dev

#    mysql
#    messages:
#      basename: i18n.messages
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test03?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
#      druid
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus
mybatis-plus:
  mapper-locations:
  type-aliases-package: com.example.springbootredisdemo03.*.entity
server:
  port: 8081
